app/models/question.py
import app.models.amazon_principle
from app.models.base_model import Column, ForeignKey, Integer, Model, String


class Question(Model):
    id = Column(Integer, primary_key=True)
    question = Column(String(1024), unique=True, nullable=False)
    amazon_principle_id = Column(
        Integer, ForeignKey("amazon_principle.id"), nullable=False
    )

    def __repr__(self):
        return f"<Question {self.question}>"

    @property
    def principle(self):
        return app.models.amazon_principle.AmazonPrinciple.query.get(
            self.amazon_principle_id
        )

    def applicable(self, story):
        return app.models.story_applicability.StoryApplicibility.query.filter_by(
            story_id=story.id, question_id=self.id
        ).first()

    @property
    def good_answers(self):
        return [
            applicability.story
            for applicability in app.models.story_applicability.StoryApplicibility.query.filter_by(
                question_id=self.id
            ).all()
            if applicability.percent_applicable >= 80
        ]

app/models/story.py
import app.models.story_applicability
from app.models.base_model import Column, ForeignKey, Integer, Model, String


class Story(Model):
    id = Column(Integer, primary_key=True)
    name = Column(String(80), unique=True, nullable=False)
    company = Column(String(80), unique=False, nullable=False)
    year = Column(Integer, unique=False, nullable=True)
    situation = Column(String(), unique=False, nullable=False)
    task = Column(String(), unique=False, nullable=False)
    action = Column(String(), unique=False, nullable=False)
    result = Column(String(), unique=False, nullable=False)
    notes = Column(String(), unique=False, nullable=False)

    def __repr__(self):
        return f"<Story situation='{self.situation}' task='{self.task}' action='{self.action}' result='{self.result}' notes='{self.notes}'>"

    def applicable(self, question):
        return app.models.story_applicability.StoryApplicibility.query.filter_by(
            story_id=self.id, question_id=question.id
        ).first()

    @property
    def questions_that_need_me(self):
        all_applicabilities = (
            app.models.story_applicability.StoryApplicibility.query.filter_by(
                story_id=self.id
            ).all()
        )
        high_applicabilities = [
            applicability
            for applicability in all_applicabilities
            if applicability.percent_applicable >= 80
        ]
        lonely_questions = [
            applicability.question
            for applicability in high_applicabilities
            if len(applicability.question.good_answers) == 1
        ]
        return lonely_questions

app/controllers/cleanup.py
from flask import redirect, render_template, request, url_for

from app.models.amazon_principle import AmazonPrinciple
from app.models.question import Question
from app.models.story import Story
from app.models.story_applicability import StoryApplicibility


def render():
    all_applicabilities = StoryApplicibility.query.all()
    for applicability in all_applicabilities:
        if applicability.story is None or applicability.question is None:
            applicability.delete()

    all_stories = Story.query.all()
    all_questions = Question.query.all()
    all_associations = StoryApplicibility.query.all()
    associations_by_relations = {
        (association.story_id, association.question_id)
        for association in all_associations
    }
    story_missing_association_counts = {
        story: len(
            [
                question
                for question in all_questions
                if (story.id, question.id) not in associations_by_relations
            ]
        )
        for story in all_stories
    }
    question_missing_association_counts = {
        question: len(
            [
                story
                for story in all_stories
                if (story.id, question.id) not in associations_by_relations
            ]
        )
        for question in all_questions
    }

    lonely_stories = [
        (story, count)
        for story, count in story_missing_association_counts.items()
        if count > 0
    ]
    lonely_questions = [
        (question, count)
        for question, count in question_missing_association_counts.items()
        if count > 0
    ]
    unfinished_stories = [
        story
        for story in all_stories
        if any(
            len(field.strip()) < 5
            for field in [
                story.situation,
                story.task,
                story.action,
                story.result,
                story.notes,
            ]
        )
    ]
    unanswred_questions = [
        question for question in all_questions if len(question.good_answers) == 0
    ]
    underanswered_questions = [
        question for question in all_questions if len(question.good_answers) == 1
    ]
    for question in underanswered_questions:
        print("Underanswered question: ", question.question)
        print("Good answers len:", len(question.good_answers))
        print("Good answers directly:", question.good_answers)
    cleanup_length = max(
        len(lonely_stories),
        len(lonely_questions),
        len(unfinished_stories),
        len(unanswred_questions),
        len(underanswered_questions),
    )

    return render_template(
        "cleanup.html",
        lonely_stories=lonely_stories,
        lonely_questions=lonely_questions,
        unfinished_stories=unfinished_stories,
        unanswred_questions=unanswred_questions,
        underanswered_questions=underanswered_questions,
        cleanup_length=cleanup_length,
    )

app/controllers/principles.py
from flask import redirect, render_template, request, url_for

from app.models.amazon_principle import AmazonPrinciple
from app.models.question import Question
from app.models.story import Story


def render_all():
    if request.method == "POST":
        name = request.form.get("name")
        principle = AmazonPrinciple.query.filter_by(name=name).first()
        if not principle:
            description = request.form.get("description")
            principle = AmazonPrinciple(name=name, description=description)
            principle.save()
    all_principles = AmazonPrinciple.query.all()
    question_counts = {
        principle.id: len(principle.questions) for principle in all_principles
    }
    return render_template(
        "principles.html",
        principles=all_principles,
        question_counts=question_counts,
    )


def render_single(principle_id):
    principle = AmazonPrinciple.query.get(principle_id)
    edited_question_id = None
    if request.method == "POST":
        if request.form.get("add"):
            question_text = request.form.get("question")
            question = Question(
                question=question_text, amazon_principle_id=principle.id
            )
            question.save()
        elif request.form.get("delete"):
            question = Question.query.get(int(request.form.get("question_id")))
            question.delete()
        elif request.form.get("edit"):
            edited_question_id = int(request.form.get("question_id"))
        elif request.form.get("update"):
            question = Question.query.get(int(request.form.get("question_id")))
            question.question = request.form.get("question")
            question.save()
        elif request.form.get("story"):
            story = Story(
                name=request.form.get("name"),
                company=request.form.get("company"),
                year=int(request.form.get("year")),
                situation=request.form.get("situation"),
                task=request.form.get("task"),
                action=request.form.get("action"),
                result=request.form.get("result"),
                notes=request.form.get("notes"),
            )
            story.save()

    questions = principle.questions
    stories = Story.query.all()
    story_count = len(stories)
    return render_template(
        "principle.html",
        principle=principle,
        questions=questions,
        edited_question_id=edited_question_id,
        stories=stories,
        story_count=story_count,
        story_columns=10,
    )

app/controllers/questions.py
from pprint import pprint

from flask import redirect, render_template, request, url_for

from app.models.amazon_principle import AmazonPrinciple
from app.models.question import Question
from app.models.story import Story
from app.models.story_applicability import StoryApplicibility


def render_all():
    all_questions = sorted(Question.query.all(), key=lambda q: q.principle.name)
    return render_template(
        "questions.html",
        all_questions=all_questions,
    )


def render_single(question_id):
    question = Question.query.get(question_id)
    if request.method == "POST":
        if request.form.get("update_ratings"):
            for input in request.form:
                if input.startswith("hidden_applicability_"):
                    story_id = int(input.split("_")[2])
                    applicability = int(request.form.get(input))
                    if applicability < 0:
                        continue
                    story_applicability = StoryApplicibility.query.filter_by(
                        story_id=story_id, question_id=question_id
                    ).first()
                    if story_applicability is None:
                        story_applicability = StoryApplicibility(
                            story_id=story_id, question_id=question_id
                        )
                    story_applicability.percent_applicable = applicability
                    story_applicability.save()
    all_stories = Story.query.all()
    applicabilities = {story.id: story.applicable(question) for story in all_stories}
    applicable_stories = sorted(
        [
            (
                story,
                applicabilities[story.id],
                len([q for q in story.questions_that_need_me if q.id != question_id]),
            )
            for story in all_stories
        ],
        key=lambda pair: (
            -(pair[1]).percent_applicable if pair[1] is not None else -1000
        ),
    )
    needy_competition = {
        story.name: [
            q.question for q in story.questions_that_need_me if q.id != question_id
        ]
        for story in all_stories
    }

    pprint(needy_competition)
    return render_template(
        "question.html", question=question, applicable_stories=applicable_stories
    )

app/controllers/stories.py
from flask import redirect, render_template, request, url_for

from app.models.amazon_principle import AmazonPrinciple
from app.models.question import Question
from app.models.story import Story
from app.models.story_applicability import StoryApplicibility


def render_single(story_id):
    story = Story.query.get(story_id)
    if request.method == "POST":
        if request.form.get("update"):
            try:
                story.year = int(request.form.get("year").strip())
            except:
                story.year = None
            story.situation = request.form.get("situation").strip()
            story.task = request.form.get("task").strip()
            story.action = request.form.get("action").strip()
            story.result = request.form.get("result").strip()
            story.notes = request.form.get("notes").strip()
            story.save()
        elif request.form.get("delete"):
            applicabilities_for_story = StoryApplicibility.query.filter_by(
                story_id=story_id
            ).all()
            for applicability in applicabilities_for_story:
                applicability.delete()
            story.delete()
            return redirect(url_for("bio.render_stories"))
        elif request.form.get("update_ratings"):
            for input in request.form:
                if input.startswith("hidden_applicability_"):
                    applicability = int(request.form.get(input))
                    if applicability < 0:
                        continue
                    question_id = int(input.split("_")[2])
                    story_applicability = StoryApplicibility.query.filter_by(
                        story_id=story_id, question_id=question_id
                    ).first()
                    if story_applicability is None:
                        story_applicability = StoryApplicibility(
                            story_id=story_id, question_id=question_id
                        )
                    story_applicability.percent_applicable = applicability
                    story_applicability.save()

    all_questions = Question.query.all()
    applicabilities = {
        question.id: story.applicable(question) for question in all_questions
    }
    quetions_that_need_me = set()
    for question_id in applicabilities:
        if applicabilities[question_id] is not None:
            if 0 > applicabilities[question_id].percent_applicable:
                applicabilities[question_id].percent_applicable = 0
                applicabilities[question_id].save()
            if 100 < applicabilities[question_id].percent_applicable:
                applicabilities[question_id].percent_applicable = 100
                applicabilities[question_id].save()
            if applicabilities[question_id].percent_applicable >= 80:
                question = Question.query.get(question_id)
                assert len(question.good_answers) >= 1
                if len(question.good_answers) == 1:
                    quetions_that_need_me.add(question)
    applicable_questions = sorted(
        [(question, applicabilities[question.id]) for question in all_questions],
        key=lambda pair: (
            -(pair[1]).percent_applicable if pair[1] is not None else -1000
        ),
    )

    return render_template(
        "story.html",
        story=story,
        question_count=len(all_questions),
        applicable_questions=applicable_questions,
        quetions_that_need_me=quetions_that_need_me,
    )


def render_all():
    all_stories = Story.query.all()
    print(all_stories)
    return render_template("stories.html", stories=all_stories)

app/routes.py
from flask import Blueprint, redirect, url_for

from tinker import export_all

export_all()

from app.controllers import cleanup, index, principles, questions, stories

bio_bp = Blueprint("bio", __name__)


@bio_bp.route("/")
def redirect_to_index():
    return redirect(url_for("bio.render_index"))


@bio_bp.route("/index", methods=["GET"])
def render_index():
    return index.render()


@bio_bp.route("/principles", methods=["GET", "POST"])
def render_principles():
    return principles.render_all()


@bio_bp.route("/principles/<principle_id>", methods=["GET", "POST"])
def render_principle(principle_id):
    return principles.render_single(principle_id)


@bio_bp.route("/stories", methods=["GET", "POST"])
def render_stories():
    return stories.render_all()


@bio_bp.route("/stories/<story_id>", methods=["GET", "POST"])
def render_story(story_id):
    return stories.render_single(story_id)


@bio_bp.route("/questions", methods=["GET", "POST"])
def render_questions():
    return questions.render_all()


@bio_bp.route("/questions/<question_id>", methods=["GET", "POST"])
def render_question(question_id):
    return questions.render_single(question_id)


@bio_bp.route("/cleanup", methods=["GET"])
def render_cleanup():
    return cleanup.render()

app/templates/cleanup.html
<!DOCTYPE html>
<html>
  <head>
    <title>Behavioral Interview Organizer</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='styles.css') }}"
    />
  </head>
  <body>
    <p class='breadcrumb'>
        <a href="{{url_for("bio.render_index")}}">home</a>
        &gt; cleanup
    </p>
    <h1>Cleanup</h1>
    <table class="highlevel">
        <thead>
            <tr>
                <th>Stories with missing associations</th>
                <th>Questions with missing associations</th>
                <th>Stories with empty sections</th>
                <th>Questions without answers</th>
                <th>Questions with one answer</th>
            </tr>
        </thead>
        <tbody>
            {% for i in range(cleanup_length) %}
            <tr>
                <td>
                    {% if lonely_stories|length > i %}
                    <span class="left">
                        <a href="{{url_for("bio.render_story", story_id=lonely_stories[i][0].id)}}">
                            {{lonely_stories[i][0].name}}
                        </a>
                    </span>
                    <span class="right">
                        {{lonely_stories[i][1]}}
                    </span>
                    {% endif %}
                </td>
                <td>
                    {% if lonely_questions|length > i %}
                    <span class="left">
                        <a href="{{url_for("bio.render_question", question_id=lonely_questions[i][0].id)}}">
                            {{lonely_questions[i][0].question[:30]}}…
                        </a>
                    </span>
                    <span class="right">
                        {{lonely_questions[i][1]}}
                    </span>
                    {% endif %}
                </td>
                <td>
                    {% if unfinished_stories|length > i %}
                    <a href="{{url_for("bio.render_story", story_id=unfinished_stories[i].id)}}">
                    {{unfinished_stories[i].name}}
                    </a>
                    {% endif %}
                </td>
                <td>
                    {% if unanswred_questions|length > i %}
                    <a href="{{url_for("bio.render_question", question_id=unanswred_questions[i].id)}}">
                    {{unanswred_questions[i].question[:30]}}…
                    </a>
                    {% endif %}
                </td>
                <td>
                    {% if underanswered_questions|length > i %}
                    <a href="{{url_for("bio.render_question", question_id=underanswered_questions[i].id)}}">
                    {{underanswered_questions[i].question[:30]}}…
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Behavioral Interview Organizer</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='styles.css') }}"
    />
  </head>
  <body>
    <h1>Index</h1>
    <ul>
      <li><a href="{{ url_for('bio.render_principles') }}">Principles</a> - general categories of question; things an interviewer is looking for</li>
      <li><a href="{{ url_for('bio.render_questions') }}">Questions</a> - questions not sorted by principle. where you'd go in an interview.</li>
      <li><a href="{{ url_for('bio.render_stories') }}">Stories</a> - stories you have to tell. Each story likely matches many questions</li>
      <li><a href="{{ url_for('bio.render_cleanup') }}">Cleanup</a> - auto-generated TODO list; missing ratings, under-specified stories, etc</li>
  </body>
</html>

app/templates/principle.html
<!DOCTYPE html>
<html>
  <head>
    <title>Behavioral Interview Organizer</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='styles.css') }}"
    />
  </head>
  <body>
    <p class='breadcrumb'>
        <a href="{{url_for("bio.render_cleanup")}}">cleanup</a> |
        <a href="{{url_for("bio.render_index")}}">home</a>
        &gt; <a href="{{ url_for("bio.render_principles") }}">principles</a>
        &gt; principle
    </p>
    <h1>{{ principle.name }}</h1>
    <table><tr>
        <td valign="top">
        <p><em>{{ principle.description }}</em></p>
        {% for question in questions %}
            {% if question.id == edited_question_id %}
                <form action="" method="post">
                    <input type="hidden" name="question_id" value="{{ question.id }}" />
                    <textarea
                        id="question"
                        name="question"
                        rows="4"
                        cols="50"
                    >{{ question.question }}</textarea
                    ><br /><br />
                    <input type="submit" name="update" value="Update" />
                    <input type="submit" name="cancel" value="Cancel" />
                </form>
            {% else %}
                <h3><a href="{{ url_for('bio.render_question', question_id=question.id) }}">{{ question.question }}</a></h3>
                <form action="" method="post">
                <input type="hidden" name="question_id" value="{{ question.id }}" />
                <input type="submit" name="edit" value="Edit" />
                <input type="submit" name="delete" value="Delete" />
                </form>
            {% endif %}

        {% endfor %}
        <hr/>
        <form action="" method="post">
            <label for="question">Add a question:</label><br />
            <textarea
                id="question"
                name="question"
                rows="4"
                cols="50"
                placeholder="Why are you so awesome?"
            ></textarea
            ><br /><br />
            <input type="submit" name="add" value="Add Question" />
        </form>
    </td>
    <td>
        <hr/>
        <form action="" method="post">
            <h3>Add a story</h3>
            <label for="name">Short name:</label>
            <input type="text" name="name" /><br/>
            <label for="company">Company:</label>
            <input type="text" name="company" /><br/>
            <label for="year">Year:</label>
            <input type="text" name="year" /><br/>

            <label for="situation">Situation:</label><br />
            <textarea
            id="situation"
            name="situation"
            rows="4"
            cols="50"
            placeholder="Set the scene and give the necessary details of your example."
            ></textarea
            ><br />

            <label for="task">Task:</label><br />
            <textarea
            id="task"
            name="task"
            rows="4"
            cols="50"
            placeholder="Describe what your responsibility was in that situation."
            ></textarea
            ><br />

            <label for="action">Action:</label><br />
            <textarea
            id="action"
            name="action"
            rows="4"
            cols="50"
            placeholder="Explain exactly what steps you took to address it."
            ></textarea
            ><br />

            <label for="result">Result:</label><br />
            <textarea
            id="result"
            name="result"
            rows="4"
            cols="50"
            placeholder="Share what outcomes your actions achieved."
            ></textarea
            ><br />

            <label for="notes">Notes:</label><br />
            <textarea
            id="notes"
            name="notes"
            rows="4"
            cols="50"
            placeholder="Things to remember if you tell the story. Context, answers to potential questions."
            ></textarea
            ><br />

            <input type="submit" name="story" value="Add Story" />
        </form>
      </td>
    </tr><tr><td>
        <h3>All Stories</h3>
        <table>
            {% for row in range(story_count // story_columns + 1) %}
                <tr>
                    {% for col in range(story_columns) %}
                        <td valign="top">
                            {% if row * story_columns + col < story_count %}
                                <a href="{{ url_for('bio.render_story', story_id=stories[row * 10 + col].id) }}">{{stories[row * 10 + col].company}}:{{ stories[row * 10 + col].name }}</a>
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </td></tr>
    </table>
  </body>
</html>

app/templates/question.html
<!DOCTYPE html>
<html>
  <head>
    <p class='breadcrumb'>
        <a href="{{url_for("bio.render_cleanup")}}">cleanup</a> |
        <a href="{{url_for("bio.render_index")}}">home</a>
        &gt; <a href="{{ url_for("bio.render_principles") }}">principles</a>
        &gt; <a href=" {{ url_for("bio.render_principle", principle_id=question.principle.id) }}">{{ question.principle.name }}</a>
        &gt; question
    </p>
    <p class='breadcrumb'>
        <a href="{{url_for("bio.render_cleanup")}}">cleanup</a> |
        <a href="{{url_for("bio.render_index")}}">home</a>
        &gt; <a href="{{ url_for("bio.render_questions") }}">question</a>
        &gt; question
    </p>
    <title>Behavioral Interview Organizer</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='styles.css') }}"
    />
  </head>
  <body>
    <h1>{{ question.question }}</h1>
    <form method="post">
        <table>
            <thead>
                <tr>
                    <th>story</th>
                    <th>co</th>
                    <th>year</th>
                    <th>relevance <input class="hidden" type="submit" id="submit_rating_updates" name="update_ratings" value="Update ratings" /></th>
                    <th title="How many other questions that need this story">ⓘ</th>
                </tr>
            </thead>
            <tbody>
                {% for story, applicability, needy_competition in applicable_stories %}
                <tr>
                    <td>
                    <a href="{{ url_for('bio.render_story', story_id=story.id) }}"> {{story.name}}</a>
                    </td>
                    <td> {{story.company}} </td>
                    <td> {{story.year}} </td>
                    <td>
                        <span class="left">
                            <input type="range" name="applicability_{{ story.id }}" min="0" max="100" step="1"
                            class="{{ 'changed' if applicability else ''}}"
                                value="{{ applicability.percent_applicable if applicability else 0 }}"
                                onclick="document.getElementById('display_rating_{{ story.id }}').innerHTML = this.value;document.getElementById('hidden_applicability_{{ story.id }}').value = this.value;this.className='changed';document.getElementById('submit_rating_updates').className=''"
                            />
                            <input type="hidden"
                                id="hidden_applicability_{{ story.id }}"
                                name="hidden_applicability_{{ story.id }}"
                                value="{{ applicability.percent_applicable if applicability else -1}}"
                            />
                        </span>
                        <span class="right" id="display_rating_{{ story.id }}">{{ applicability.percent_applicable if applicability }}</span>
                        </span>
                    </td>
                    <td align="center">
                        <strong>{{ needy_competition }}</strong>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
  </body>
</html>

app/templates/questions.html
<!DOCTYPE html>
<html>
  <head>
    <p class='breadcrumb'>
        <a href="{{url_for("bio.render_cleanup")}}">cleanup</a> |
        <a href="{{url_for("bio.render_index")}}">home</a>
        &gt; questions
    </p>
    <title>Behavioral Interview Organizer</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='styles.css') }}"
    />
  </head>
  <body>
    <p class='breadcrumb'>
        <a href="{{url_for("bio.render_index")}}">home</a>
        &gt; questions
    </p>
    <h1>Questions</h1>
    <table class="highlevel">
        <thead>
            <th>Question</th>
            <th>Category</th>
            <th>Good answers</th>
        </thead>
        <tbody>
            {% for question in all_questions %}
                <tr>
                    <td>
                        <a href="{{ url_for('bio.render_question', question_id=question.id) }}">
                            {{ question.question[:40] }}{{ "…" if question.question|length > 40 }}
                        </a>
                    </td>
                    <td>
                        <a href="{{ url_for('bio.render_principle', principle_id=question.principle.id) }}">
                            {{ question.principle.name }}
                        </a>
                    </td>
                    <td>{{ question.good_answers|length }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
  </body>
</html>

app/templates/stories.html
<!DOCTYPE html>
<html>
  <head>
    <title>Behavioral Interview Organizer</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='styles.css') }}"
    />
  </head>
  <body>
    <p class='breadcrumb'>
        <a href="{{url_for("bio.render_cleanup")}}">cleanup</a> |
        <a href="{{url_for("bio.render_index")}}">home</a>
        &gt; stories
    </p>
    <h1>Stories</h1>
    <table>
        <thead>
            <tr>
                <th>
                    Story
                </th>
                <th>
                    Setting
                </th>
                <th>
                    Year
                </th>
                <th>
                    is the only good story for:
                </th>
            </tr>
        </thead>
        <tbody>
            {% for story in stories: %}
            <tr class="story">
                <td valign="center"><a href="{{ url_for("bio.render_story", story_id=story.id) }}">{{ story.name }}</a></td>
                <td valign="center">{{ story.company }}</td>
                <td valign="center">{{ story.year }}</td>
                <td>
                {% if story.questions_that_need_me %}
                    <ul>
                        {% for question in story.questions_that_need_me %}
                        <li><a href="{{ url_for("bio.render_question", question_id=question.id)}}">(link)</a> {{ question.question }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </body>
</html>